### PR TITLE
Preserve order in class path entries

### PR DESCRIPTION
**Pull request by Fuud**
If there are several versions of a single class in class-path (for example if there are patches for 3rd party libraries) order of class-path elements is matter.

This PR provides ordering for class-path entries. For example:
```
node.x(VX.CLASSPATH).add(jar1);
node.x(VX.CLASSPATH).add(jar2);
```
Then jar1 will be earlier in class-path that jar2 and classes from jar1 will have precedence.

Also, I added Idea files to .gitignore. If it is undesirable I can remove this file from the commit.

### CODE REVIEW

**Comment by aragozin** [comment]
Property name is improper name to put a class path priority.

Imagine

    node.x(VX.CLASSPATH).add(jar1);
    node.x(VX.CLASSPATH).remove(jar1);

In result jar1 would be added to classpath. 

I suggest to put priority into property value (currently classpath tweak starts either with + or -, you could add optional !<n> which would be interpreted as priority during classpath generation).

**Comment by Fuud** [comment]
>In result jar1 would be added to classpath.
Yes. But the problem was in processing order. It was wrong to process in other order than action was added. It was inspired by the idea that new entries should be added to the beginning of classpath.
Now it was fixed by separate classpath into inherited and new path. Deletion performing by removing from both parts and addition is performed by adding to new part only. At the end of classpath construction inherited classpath is appended to the new part.

>I suggest to put priority into property value
I will do it.

**Comment by Fuud** [comment]
> I suggest to put priority into property value

Done.

**Comment by aragozin** [comment]
Merged

**Pull request closed without merging**
